import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Intro from '../components/Intro'
import Services from '../components/Services'
import Progress from '../components/Progress'
import Features from '../components/Features'
import Faq from '../components/Faq'
import Meeting from '../components/Meeting'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	  <Intro/>
	  <Services/>
	  <Progress/>
	  <Features/>
	  <Faq/>
	  <Meeting/>
	  <Footer/>

	
    </div>
  )
}
